In [1]:
#imports
from datascience import *
import numpy as np

# These lines set up graphing capabilities.
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

In [2]:
#declaring an array to use in the next couple code blocks
arr = make_array(5, 3, 8, 9, 2)
arr

array([5, 3, 8, 9, 2])

In [ ]:
# Finds the maximum element of the array
max(arr)

In [ ]:
# Finds the minimum element of the array
min(arr)

In [ ]:
# Number of elements inside array arr
len(arr)

In [ ]:
# Small Demo on rounding which shows how the round function works for different values
print ("round(1.4) = ", round(1.4))
print ("round(1.5) = ", round(1.5))
print ("round(1.6) = ", round(1.6))
print ("round(-1.6) = ", round(-1.6))

In [3]:
# Round can also be done in batches using np.round which
# will apply the round function to each element of the array
arr = make_array(1.4, 1.5, 1.6, -1.6)
np.round(arr)

array([ 1.,  2.,  2., -2.])

In [ ]:
# Abs simply takes the absolute value of the element
abs(-5)

In [4]:
# Applies the abs function to each element of the array
np.abs(make_array(-2, -1, 0, 1, 2, -3.5))

array([2. , 1. , 0. , 1. , 2. , 3.5])

In [5]:
# Finds the average of the elements of the array
np.average(make_array(2,3,4,5))

3.5

In [6]:
# Finds the mean of the elements of the array
np.mean(make_array(2,3,4,5))

3.5

In [ ]:
# np.arange with one parameter gives an array with 
# every value from 0 to the value passed in minus 1
np.arange(5)

In [ ]:
# np.arange with two parameters returns an array with 
# every value starting with the first parameter
# up to the second parameter minus 1
np.arange(5,10)

In [ ]:
# np.arange with three parameters does the same thing
# as the two parameter version, except it uses the 
# third parameter as the incrementer instead of doing 
# plus 1 each time
np.arange(6,10,2)

In [ ]:
# The .item(x) function returns the xth item of the array
arr = make_array(2,5,1,7)
arr.item(2)

In [ ]:
# Returns an empty table
Table()

In [ ]:
# Returns the table defined in the csv file which the path
# parameter references
# NOTE: I HAVE NOT DEFINED A "something.csv" FILE
# IN THIS DIRECTORY SO THIS WILL ERROR
Table.read_table("something.csv")

In [ ]:
# Declares a table called courses which we will use in the coming functions
courses = Table().with_columns(
    "Course", make_array("INT5", "CS16", "PHYS1", "MATH4A"),
    "Lecture Time", make_array("TR 9:30-9:45", "MW 10:00-11:15", "MWF 9:00 - 9:50", "MW 10:00-11:15"),
    "Enrolled", make_array(72, 91, 249, 103),
    "Capacity", make_array(75, 100, 250, 125))
courses

In [ ]:
# Returns the number of rows in the table
courses.num_rows

In [ ]:
# Returns the number of columns in the table
courses.num_columns

In [ ]:
# Returns an array containing all the labels for the table
courses.labels

In [ ]:
# Creates a new column in our table called "Available Spots"
# which has the capacity - enrolled for the course
courses.with_column("Available Spots", courses.column("Capacity") - courses.column("Enrolled"))


In [ ]:
# Returns an array with the values of the column
# specified by the parameter
courses.column("Course")

In [ ]:
# Returns a new table which is the same as our
# original table but only contains the columns specified
courses.select("Course", "Lecture Time")

In [ ]:
# Returns a new table which is the same as our
# original table but doesn't contain the columns specified
courses.drop("Course", "Lecture Time")

In [ ]:
# Returns a new table with the "Course" label
# changed to "Class Name"
courses.relabeled("Course", "Class Name")

In [ ]:
# Returns a new table with only the rows specified 
# by the parameter which can either be an array of 
# values or a single value
courses.take([0,1])

In [ ]:
# Returns a new table sorted by the "Class Name" parameter
# if the column specified is of string type it is sorted alphabetically
# if the column specified is of numerical type it is sorted numerically
# You can add an additional parameter descending=True to reverse the order
courses.sort("Course")

In [ ]:
# Returns a new table which keeps only the rows where
# the value of the column specified as the first parameter
# meet the condition defined as the second parameter
# See list of predicates for more options
courses.where("Capacity", are.above(100))

In [ ]:
# Create a new table which has each unique value of the column 
# specifed by our parameter along with the number of rows which have that value
courses.group("Lecture Time")

In [ ]:
# Creates a scatter plot with the first value as the x-axis
# and the second value as the y-axis
courses.scatter("Enrolled", "Capacity")

Some practice problems(using the original courses table which we have redefined below):

In [ ]:
# Declares a table called courses which we will use in the coming functions
courses = Table().with_columns(
    "Course", make_array("INT5", "CS16", "PHYS1", "MATH4A"),
    "Lecture Time", make_array("TR 9:30-9:45", "MW 10:00-11:15", "MWF 9:00 - 9:50", "MW 10:00-11:15"),
    "Enrolled", make_array(72, 91, 249, 103),
    "Capacity", make_array(75, 100, 250, 125))
courses

Write a line of code which returns a single number indicating the highest capacity for any course

Copy your solution from the previous question and modify it so that the return values is the name of the course with the highest capacity

Write a line of code which gives us an array of course names sorted by enrollment percentage (Enrolled/Capacity). 

Write a line of code which returns a single number indicating the total number of students enrolled in courses which have more than 100 students.